[workspace]
resolver = "2"
members = ["cli", "rongta", "ai"]
default-members = ["cli"]

[workspace.package]
version = "0.3.5"
edition = "2024"
authors = ["Cesar <58753718+Ces-D@users.noreply.github.com>"]

[workspace.dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.43", features = ["cargo", "derive"] }
chrono = "0.4.42"
env_logger = "0.11.8"
log = "0.4.27"
ascii = "1.1.0"
escpos = "0.16.0"
serde = "1.0.228"
rand = "0.9.2"
strum = { version = "0.27", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
async-openai = "0.30.1"
comrak = "0.49"

rongta = { path = "./rongta" }
ai = { path = "./ai" }
