[package]
name = "tiptap"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
path = "tiptap.rs"

[dependencies]
log.workspace = true
serde.workspace = true
serde_json.workspace = true
