name: konan
services:
  server:
    container_name: konan-server
    build:
      context: ../
      dockerfile: ./docker/server.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
  web:
    container_name: konan-web
    build:
      context: ../konan_web
      dockerfile: ../docker/web.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env
