[package]
name = "rongta"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
path = "rongta.rs"

[dependencies]
anyhow.workspace = true
log.workspace = true
escpos.workspace = true
strum.workspace = true
