[package]
name = "lambda_shared"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
path = "lambda_shared.rs"

[dependencies]
serde.workspace = true
lambda_runtime.workspace = true
aws-config.workspace = true
aws-sdk-iotdataplane.workspace = true
